### ISSUE TITLE
Little Mistake in 3.1-logistic-regression.ipynb 

### ISSUE THREAD

**Issue by ROBINADC** [zergtant/pytorch-handbook#14]
net=LR() 
criterion=nn.CrossEntropyLoss() # 使用CrossEntropyLoss损失
optm=torch.optim.Adam(net.parameters()) # Adam优化
epochs=1000 # 训练**10000**次

应该是
epochs=1000 # 训练**1000**次

**Comment by zergtant** [comment]
好的，我核对下修改
