### ISSUE TITLE
FastAI 抱团取暖

### ISSUE THREAD

**Issue by AutuanLiu** [zergtant/pytorch-handbook#18]
关于fastai/course-v3和NLA的个人笔记，断断续续的[学习笔记](https://github.com/AutuanLiu/Fastai-Notes-V3)
1. https://github.com/AutuanLiu/Fastai-Notes-V3
2. [AutuanLiu/PyTorch-ML: Implement DNN or ML models and advanced policies with PyTorch.(Include experiment)](https://github.com/AutuanLiu/PyTorch-ML)

- FastAI 的相关课程
1. [fastai/course-v3: The 3rd edition of course.fast.ai](https://github.com/fastai/course-v3)
2. [fastai/numerical-linear-algebra: Free online textbook of Jupyter notebooks for fast.ai Computational Linear Algebra course](https://github.com/fastai/numerical-linear-algebra)

关于 PyTorch 的书籍，可以帮忙

- 邮箱
autuanliu@163.com

**Comment by zergtant** [comment]
> 关于fastai/course-v3和NLA的个人笔记，断断续续的[学习笔记](https://github.com/AutuanLiu/Fastai-Notes-V3)
> 
>     1. https://github.com/AutuanLiu/Fastai-Notes-V3
> 
>     2. [AutuanLiu/PyTorch-ML: Implement DNN or ML models and advanced policies with PyTorch.(Include experiment)](https://github.com/AutuanLiu/PyTorch-ML)
> 
> 
>     * FastAI 的相关课程
> 
> 
>     1. [fastai/course-v3: The 3rd edition of course.fast.ai](https://github.com/fastai/course-v3)
> 
>     2. [fastai/numerical-linear-algebra: Free online textbook of Jupyter notebooks for fast.ai Computational Linear Algebra course](https://github.com/fastai/numerical-linear-algebra)
> 
> 
> 关于 PyTorch 的书籍，可以帮忙
> 
>     * 邮箱
>       [autuanliu@163.com](mailto:autuanliu@163.com)

我想找人一起翻一下fastai的文档，不知道你有没有兴趣 另外你qq多少，加下我吧
744978026 谢谢，哈

**Comment by AutuanLiu** [comment]
@zergtant fastai 的文档省略了很多细节 可能不是很好翻 qq 1569179236
