### ISSUE TITLE
Anaconda 的清华源又可以用了

### ISSUE THREAD

**Issue by YoungForest** [zergtant/pytorch-handbook#41]
[公告: **Anaconda 镜像即将恢复**](https://mirrors4.tuna.tsinghua.edu.cn/news/#restore-anaconda)

[地址](https://mirrors4.tuna.tsinghua.edu.cn/help/anaconda/)

**Comment by zergtant** [comment]
哦了

**Comment by zergtant** [comment]
已经改了
