### ISSUE TITLE
404 not found了

### ISSUE THREAD

**Issue by njj14041** [zergtant/pytorch-handbook#44]
第二章第一节第四部分，就数据处理那个，网页404了

**Comment by sc779733661** [comment]
我也发现同样的问题，用VPN也打不开

**Comment by Becmamba** [comment]
我也是

**Comment by linkworb** [comment]
https://github.com/zergtant/pytorch-handbook/blob/master/chapter2/2.1.4-pytorch-basics-data-loader.ipynb这个是正确的地址，就是去源码里找那个文件，估计是作者的链接写错了。

**Comment by sc779733661** [comment]
> [https：/github.com/zergant/py手电筒-手册/blob/主/章2/2.1.4-py手电-基础-数据加载器.ipynb这个是正确的地址，就是去源码里找那个文件，估计是作者的链接写错了。](https://github.com/zergtant/pytorch-handbook/blob/master/chapter2/2.1.4-pytorch-basics-data-loader.ipynb%E8%BF%99%E4%B8%AA%E6%98%AF%E6%AD%A3%E7%A1%AE%E7%9A%84%E5%9C%B0%E5%9D%80%EF%BC%8C%E5%B0%B1%E6%98%AF%E5%8E%BB%E6%BA%90%E7%A0%81%E9%87%8C%E6%89%BE%E9%82%A3%E4%B8%AA%E6%96%87%E4%BB%B6%EF%BC%8C%E4%BC%B0%E8%AE%A1%E6%98%AF%E4%BD%9C%E8%80%85%E7%9A%84%E9%93%BE%E6%8E%A5%E5%86%99%E9%94%99%E4%BA%86%E3%80%82)

Thanks，我之前是clone下来用pycharm看。没注意到有个字母是打错了。

**Comment by littlefis** [comment]
两周前我把这个改了发了pull request，但还没被通过

**Comment by zergtant** [comment]
改完了
