### ISSUE TITLE
3_neural_networks_tutorial中nn.Linear的输入特征数量

### ISSUE THREAD

**Issue by gandad** [zergtant/pytorch-handbook#53]
如下代码，其中 self.fc1 = nn.Linear(16 * 5 * 5, 120)，不明白，Linear的输入特数量应该是通道的数量乘上图片的大小，即16*32*32，与filter无关吧？
`
class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 5x5 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
`

**Comment by onlyonewater** [comment]
它这是大小为16*5*5的池化层连接到全连接啊，全连接的大小为120，所以是（16*5*5,120）吧？

**Comment by onlyonewater** [comment]
16 * 5 * 5

**Comment by gandad** [comment]
明白了，其实这里的5\*5是图像featuremap的大小，碰巧与kernel size相同
```
        # Max pooling over a (2, 2) window
        # conv1(x)=>32->(32-5)/1+1=28; 28 downsampling to=>14
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2)) 
        # If the size is a square you can only specify a single number
        # conv1(x)=>14->(14-5)/1+1=10; 10 downsampling to=>5
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
```
