### ISSUE TITLE
pytorch for deeplearning环境不可用

### ISSUE THREAD

**Issue by LittlelittleZ** [zergtant/pytorch-handbook#54]
根据手册安装好相应固件后，在Jupter Notebook上无法运行pytorch，python3可以使用，但是使用pytorch后编辑页面显示“Dead kermel”，Jupter Notebook显示“ImportError: DLL load failed: 找不到指定的模块”，请问这是怎么回事呢

**Comment by zergtant** [comment]
https://github.com/pytorch/pytorch/issues/4518#issuecomment-384195186
