### ISSUE TITLE
PyTorch 基础 : 张量部分内容修改的建议

### ISSUE THREAD

**Issue by Mage-White** [zergtant/pytorch-handbook#62]
初始化这一块，个人觉得需要添加torch.randn( )，并且比较一下torch.randn( )和torch.rand( )的区别。
# 使用[0,1]均匀分布随机初始化二维数组
rand = torch.rand(5, 3)
rand
#使用标准正太分布随机初始化二维数组
randn = torch.randn(5, 3)
randn

**Comment by zergtant** [comment]
一个均匀分布，一个是标准正态分布，其他没区别
