### ISSUE TITLE
Collecting package metadata: done Solving environment: failed  PackagesNotFoundError: The following packages are not available from current channels:    - pytorch   - cuda92

### ISSUE THREAD

**Issue by zhengxinvip** [zergtant/pytorch-handbook#7]

**Comment by zhengxinvip** [comment]
PackagesNotFoundError: The following packages are not available from current channels:

  - pytorch
  - cuda92

Current channels:

  - https://conda.anaconda.org/pytorch/win-32
  - https://conda.anaconda.org/pytorch/noarch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/win-32
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/noarch
  - https://repo.anaconda.com/pkgs/main/win-32
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/win-32
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/win-32
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-32
  - https://repo.anaconda.com/pkgs/msys2/noarch

**Comment by zhengxinvip** [comment]
what should I do next？ thanks.

**Comment by zergtant** [comment]
try
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
https://conda.anaconda.org/pytorch/
