### ISSUE TITLE
qq群管理的行为真的不行

### ISSUE THREAD

**Issue by zjfan7** [zergtant/pytorch-handbook#95]
在4群里提了一下，我们几个新手建个小群多交流一下，想着我们的问题可能太简单了，在大群里问怕影响到大家，然后又朋友建了个群，就被踢了，说了两句，也给踢了？？直接踢了？？我们做的不对或者您不能容忍，至少提醒一下吧，直接踢了真的让人无话可说了。

**Comment by zergtant** [comment]
是有什么话不能在大群说吗，把建小群发广告说的这么清新脱俗。
